// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: topus/health/v1/health.proto

// 链路预检（health）服务：行走骨架第一刀。
// 用途：agent 批量纳管前，先在样本机跑一次 Ping 验证到 server 的 gRPC 链路可达
// （方案《纳管批次与接入安全》§3.8 测试命令）。本接口不需 secret、不需证书。

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_topus_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topus_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_topus_health_v1_health_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                 // 链路通且 server 正常 = true
	ServerVersion  string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`       // server 版本（便于排查版本不一致）
	ServerTimeUnix int64                  `protobuf:"varint,3,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"` // 服务端 Unix 时间（便于排查时钟漂移）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_topus_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_topus_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_topus_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingReply) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

var File_topus_health_v1_health_proto protoreflect.FileDescriptor

const file_topus_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1ctopus/health/v1/health.proto\x12\x0ftopus.health.v1\"\r\n" +
	"\vPingRequest\"l\n" +
	"\tPingReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12(\n" +
	"\x10server_time_unix\x18\x03 \x01(\x03R\x0eserverTimeUnix2J\n" +
	"\x06Health\x12@\n" +
	"\x04Ping\x12\x1c.topus.health.v1.PingRequest\x1a\x1a.topus.health.v1.PingReplyB>Z<github.com/Jingk97/topus-server/api/topus/health/v1;healthv1b\x06proto3"

var (
	file_topus_health_v1_health_proto_rawDescOnce sync.Once
	file_topus_health_v1_health_proto_rawDescData []byte
)

func file_topus_health_v1_health_proto_rawDescGZIP() []byte {
	file_topus_health_v1_health_proto_rawDescOnce.Do(func() {
		file_topus_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topus_health_v1_health_proto_rawDesc), len(file_topus_health_v1_health_proto_rawDesc)))
	})
	return file_topus_health_v1_health_proto_rawDescData
}

var file_topus_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_topus_health_v1_health_proto_goTypes = []any{
	(*PingRequest)(nil), // 0: topus.health.v1.PingRequest
	(*PingReply)(nil),   // 1: topus.health.v1.PingReply
}
var file_topus_health_v1_health_proto_depIdxs = []int32{
	0, // 0: topus.health.v1.Health.Ping:input_type -> topus.health.v1.PingRequest
	1, // 1: topus.health.v1.Health.Ping:output_type -> topus.health.v1.PingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_topus_health_v1_health_proto_init() }
func file_topus_health_v1_health_proto_init() {
	if File_topus_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topus_health_v1_health_proto_rawDesc), len(file_topus_health_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topus_health_v1_health_proto_goTypes,
		DependencyIndexes: file_topus_health_v1_health_proto_depIdxs,
		MessageInfos:      file_topus_health_v1_health_proto_msgTypes,
	}.Build()
	File_topus_health_v1_health_proto = out.File
	file_topus_health_v1_health_proto_goTypes = nil
	file_topus_health_v1_health_proto_depIdxs = nil
}
